OddorEven/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('play', include('game.urls'))

]

game/urls.py
from home.models import *
from django.contrib.auth.models import User
from django.urls import include, path
from . import views

app_name = 'game'

urlpatterns = [

    path('', views.index,name='home'),

]

home/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path
from . import  views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('signup/', views.register,name='register'),

]

game/models.py
from django.db import models
from home.models import *
from .views import *
from home.views import *
from django.utils.timezone import now #import timezone

# Create your models here.
class Result(models.Model):
    BET_CHOICES = (
        ('ODD', 'ODD'),
        ('EVEN', 'EVEN'),
    )

    time = models.DateTimeField()
    result = models.CharField(choices=BET_CHOICES,max_length=50, null=True,blank=True)


    def __str__(self):
        return self.result

class Bet(models.Model):
    BET_CHOICES = (
        ('ODD', 'ODD'),
        ('EVEN', 'EVEN'),
    )
    WIN_OR_LOSE = (
        ('WIN', 'WIN'),
        ('LOSE', 'LOSE'),
        ('PENDING', 'PENDING'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    bet = models.IntegerField(default=5)
    choice = models.CharField(choices=BET_CHOICES,max_length=50, null=True,blank=True)
    status = models.CharField(choices=WIN_OR_LOSE, max_length=50,default='PENDING')
    result = models.ForeignKey(Result, on_delete=models.CASCADE,null=True,blank=True)

    def __str__(self):
        return self.choice

#==================== Sandy model structure =======================//
BET_CHOICES = (
    ('ODD', 'ODD'),
    ('EVEN', 'EVEN'),
)

class Bet_Room(models.Model):
    room_name = models.CharField(max_length=150,null=False,blank=False)
    result = models.CharField(choices=BET_CHOICES,max_length=50, null=True,blank=True) #initialize with null
    participants = models.ManyToManyField(User, through='Bet_Participants') #returns list of participants
    is_open = models.BooleanField(default=True)
    is_finish = models.BooleanField(default=False)

    def __str__(self):
        return self.room_name

    def get_result(self):
        return self.result

class Bet_Participants(models.Model):
    bet = models.IntegerField(default=0)
    choice = models.CharField(choices=BET_CHOICES,max_length=50, null=False,blank=False)
    person = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Bet_Room, on_delete=models.CASCADE)
    date_participate = models.DateTimeField(default=now)

    def result(self):
        if self.room.get_result == self.choice:
            return "WIN"
        else:
            return "LOSE"

home/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,related_name="profile") # Additional Related name profile
    address = models.TextField(max_length=200,blank=True)
    birthday = models.DateField(null=True, blank=True)
    balance = models.IntegerField(default=100)

    def __str__(self):
        return  self.user.username

home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30,required=False,help_text='Optional')
    last_name = forms.CharField(max_length=30,required=False,help_text='Optional')
    email = forms.EmailField(max_length=200,help_text='Required. Enter a Valid Email Address')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

game/views.py
from django.shortcuts import render
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect

# Create your views here.
from django.contrib.auth.models import User
from home.models import Profile
# Create your views here.

def index(request):
    get_balance = Profile.objects.get(user=request.user.id)
    balance = get_balance.balance
    context ={
        'balance':balance,
              }

    return render(request,'game/home.html', context)

home/views.py
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect
from .forms import SignUpForm
# Create your views here.
from django.contrib.auth.models import User


def home(request):
    context = {}

    return render(request, 'home/home.html', context)


def register(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('home')
    else:
        form = SignUpForm()
    return render(request, 'home/signup.html', {'form': form})

templates/game/home.html
{% extends 'home/base.html' %}

{% block content %}

    <div class="container vh-100">
        <div class="row">
            <div class="col-4"></div>
            <div class="col-4 text-center">
                <br>
                <h1>Odd or Even</h1>
            </div>
            <div class="col-4"></div>
        </div>
        <hr>
        <div class="row ">
            <div class="col-6 text-right">
                <button type="button" class="btn btn-primary btn-rounded">Odd</button>
            </div>
            <div class="col-6 text-left">
                <button type="button" class="btn btn-default btn-rounded">Even</button>

            </div>
        </div>
    <p>Balance : {{ balance }}</p>
    </div>


{% endblock %}

templates/home/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Home</title>
   {% include 'home/links.html' %}
</head>
<body>

{% include 'home/nav.html' %}

{% block content %}

{% endblock %}

</body>
{% include 'home/js.html' %}
</html>

templates/home/home.html
{% extends 'home/base.html' %}
{% load static %}

{% block content %}
     <div class="container">

      <!--Section: Blog v.4-->
      <section class="section mt-5 pb-3 wow fadeIn">
    <!-- Card image -->
     <div class="row">
          <div class="col-md-12">
            <!-- Card -->
            <div class="card card-cascade wider reverse">

              <!-- Card image -->
              <div class="view view-cascade overlay">
                <img class="card-img-top" src="https://mdbootstrap.com/img/Photos/Slides/img%20(134).jpg" alt="Card image cap">
                <a href="#!">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>

            </div>
          </div>
     </div>
      </section>
     </div>

{% endblock %}

templates/home/js.html
{% load static %}

<!-- JQuery -->
<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript"
        src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>

templates/home/links.html
{% load static %}

 <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <!-- Google Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">

templates/home/nav.html
{% load static %}
<!--Navbar-->
<nav class="navbar navbar-expand-lg navbar-dark info-color">

    <!-- Navbar brand -->
    <a class="navbar-brand" href="{% url 'home:home' %}">Try yo Luck !</a>

    <!-- Collapse button -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
            aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Collapsible content -->
    <div class="collapse navbar-collapse" id="basicExampleNav">

        <!-- Links -->
        <ul class="navbar-nav mr-auto">
            <li class="nav-item
                {% if request.path == '/' %}
                       active
                    {% endif %}">
                <a class="nav-link" href="{% url 'home:home' %}">Home


                </a>
            </li>
            <li class="nav-item  {% if request.path == 'game' %}
                       active
                    {% endif %}">
                <a class="nav-link" href="{% url 'game:home' %}">Play

                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Todo App
                    {% if request.path == 'todo' %}
                        <span class="sr-only">(current)</span>
                    {% endif %}
                </a>
            </li>

            <!-- Dropdown -->


        </ul>
        <!-- Links -->

        <ul class="navbar-nav ml-auto nav-flex-icons">


            {% if user.is_authenticated %}

                <li class="nav-item">
                <span class="nav-link">Hi! {{ user.username }}</span>
                </li>

                <li class="nav-item avatar dropdown">

                    <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-55" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        <img src="{% static 'img/user.png' %}"
                             class="rounded-circle z-depth-0"
                             alt="avatar image">
                    </a>
                    <div class="dropdown-menu dropdown-menu-lg-right dropdown-secondary"
                         aria-labelledby="navbarDropdownMenuLink-55">
                         <a class="dropdown-item" href="#">Profile</a>
                        <a class="dropdown-item" href="{% url 'home:logout' %}?next={% url 'home:home' %}">Logout</a>


                    </div>
                </li>

            {% else %}
                <li class="nav-item  {% if request.path == '/login/' %}
                        active
                    {% endif %}">
                    <a href="{% url 'home:login' %}" class="nav-link waves-effect waves-light"><i
                            class="fas fa-sign-in-alt"></i>
                        Login
                    </a>
                </li>

                <li class="nav-item  {% if request.path == '/signup/' %}
                        active
                    {% endif %}">

                    <a href="{% url 'home:register' %}" class="nav-link waves-effect waves-light"><i class="fas fa-edit"></i>
                        Register


                    </a>
                </li>

            {% endif %}

        </ul>


    </div>
    <!-- Collapsible content -->

</nav>
<!--/.Navbar-->

templates/home/signup.html
{% load widget_tweaks %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login</title>
   {% include 'home/links.html' %}
</head>
<body class="stylish-color">
{% include 'home/nav.html' %}
<br>
<div class="container">
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6"><!-- Default form register -->
            {% if user.is_authenticated %}
                {% include 'home/404.html' %}
            {% else %}
                <!-- Material form register -->
            <div class="card animated jackInTheBox">

                <h5 class="card-header info-color white-text text-center py-4">
                    <strong>Sign up</strong>
                </h5>

                <!--Card content-->
                <div class="card-body px-lg-5 pt-0">

                    <!-- Form -->

                    <form method="post" class="text-center" style="color: #757575;" action="{% url 'register' %}">
                        {% csrf_token %}
                        {% if form.errors %}
                            <br>
                            <div class="alert alert-danger alert-dismissible fade show text-left" role="alert">
                                <p>{{ form.first_name.errors.as_text }}</p>
                                <p>{{ form.last_name.errors.as_text }}</p>
                                <p>{{ form.username.errors.as_text }}</p>
                                <p>{{ form.email.errors.as_text }}</p>
                                <p>{{ form.password1.errors.as_text }}</p>
                                <p>{{ form.password2.errors.as_text }}</p>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endif %}

                        <div class="form-row">

                            <div class="col">
                                <!-- First name -->
                                <div class="md-form">

                                    {{ form.first_name|add_class:"form-control" }}
                                    <label for="materialRegisterFormFirstName">First name</label>
                                </div>
                            </div>
                            <div class="col">
                                <!-- Last name -->
                                <div class="md-form">

                                    {{ form.last_name|add_class:"form-control" }}
                                    <label for="materialRegisterFormLastName">Last name</label>
                                </div>
                            </div>
                        </div>
                        <div class="md-form mt-0">

                            {{ form.username|add_class:"form-control" }}
                            <label for="">Username</label>
                        </div>
                        <!-- E-mail -->
                        <div class="md-form mt-0">

                            {{ form.email|add_class:"form-control" }}
                            <label for="materialRegisterFormEmail">E-mail</label>
                        </div>

                        <!-- Password -->
                        <div class="md-form">

                            {{ form.password1|add_class:"form-control" }}

                            <label for="materialRegisterFormPassword">Password</label>
                            <small id="materialRegisterFormPasswordHelpBlock" class="form-text text-muted mb-4">
                                At least 8 characters and 1 digit
                            </small>
                        </div>
                        <div class="md-form">

                            {{ form.password2|add_class:"form-control" }}
                            <label for="materialRegisterFormPassword">Confirm Password</label>

                        </div>


                        <!-- Sign up button -->
                        <button class="btn btn-outline-info btn-rounded btn-block my-4 waves-effect z-depth-0"
                                type="submit">Sign in
                        </button>

                        <!-- Register -->
                        <p>Already a member?
                            <a href="{% url 'login' %}">Sign in</a>
                        </p>

                        <hr>

                        <!-- Terms of service -->
                        <p>By clicking
                            <em>Sign up</em> you agree to our
                            <a href="" target="_blank">terms of service</a>

                    </form>
                    <!-- Form -->

                </div>

            </div>
            <!-- Material form register -->
            {% endif %}
            <div class="col-3"></div>
        </div>
    </div>
</div>
</body>
{% include 'home/js.html' %}
</html>